package narrative

import (
	"bytes"
	"encoding/gob"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/exaroth/narrative/pkg/kitten"
	"github.com/exaroth/narrative/pkg/phonemizer"
	"github.com/exaroth/narrative/pkg/preprocessor"
	"github.com/exaroth/narrative/pkg/sentencizer"
)

// Represents single text source
type Source struct {
	pproc      *preprocessor.Preprocessor
	phonemizer *phonemizer.Phonemizer
	ttsClient  *kitten.Kitten
	// Raw sentence data
	data []string
	// Current sentence number
	sentenceNum int
	// Id of the text source
	id string
	// Sentence waveform data cache
	cache_buf map[int][]float32
	// Buffer size
	buf_size int
	mut      *sync.Mutex
}

// Initialize new source instance.
func InitSource(
	path string, sentence_n, buf_size int,
	pproc *preprocessor.Preprocessor,
	phonemizer *phonemizer.Phonemizer,
	ttsClient *kitten.Kitten,
) (*Source, error) {
	data, err := LoadTextSource(path)
	if err != nil {
		return nil, err
	}

	return &Source{
		data:        data.Data,
		id:          data.Id,
		pproc:       pproc,
		phonemizer:  phonemizer,
		ttsClient:   ttsClient,
		sentenceNum: sentence_n,
		cache_buf:   make(map[int][]float32),
		buf_size:    buf_size,
		mut:         &sync.Mutex{},
	}, nil
}

// Retrieve raw sentence data.
func (s *Source) getRawSentence(n int) string {
	if n < 0 || n > len(s.data)-1 {
		// should never happen
		panic(fmt.Sprintf("Invalid sentence number passed %d", n))
	}
	return s.data[n]
}

// Retrieve raw sentence data for current sentence num.
func (s *Source) getCurrentRawSentence() string {
	return s.getRawSentence(s.sentenceNum)
}

// Retrieve phonemized version of sentence at index n.
func (s *Source) getPhonemes(n int) (string, error) {
	p_sentence := s.pproc.ProcessSentence(s.getCurrentRawSentence())
	return s.phonemizer.Phonemize(p_sentence)
}

// Retrieve phonemized version of sentence stored
// at idx == sentenceNum.
func (s *Source) getCurrentPhonemes() (string, error) {
	return s.getPhonemes(s.sentenceNum)
}

// Generate waveform data for sentence at given index
func (s *Source) generateWaveformData(n int) ([]float32, error) {
	phonemized, err := s.getPhonemes(n)
	if err != nil {
		return nil, err
	}
	return s.ttsClient.RunInference(phonemized)
}

// Retrieve buffered waveform data generated by tts client.
func (s *Source) getBufferedData(n int) []float32 {
	s.mut.Lock()
	defer s.mut.Unlock()
	if v, ok := s.cache_buf[n]; ok {
		return v
	}
	return nil
}

// Update buffer cache with data.
func (s *Source) updateBufferedData(n int, data []float32) {
	s.mut.Lock()
	defer s.mut.Unlock()
	s.cache_buf[n] = data
}

// Retrieve waveform data for given sentence
func (s *Source) getWaveformData(n int) ([]float32, error) {
	if v := s.getBufferedData(n); v != nil {
		fmt.Println(v)
		return v, nil
	}
	d, err := s.generateWaveformData(n)
	if err != nil {
		return nil, err
	}
	s.updateBufferedData(n, d)
	return d, nil
}

// Retrieve waveform data for current sentence.
func (s *Source) getCurrentSentenceWaveformData() ([]float32, error) {
	return s.getWaveformData(s.sentenceNum)
}

// Update buffer cache with sentence data.
func (s *Source) updateCacheBuffer() error {
	var wg sync.WaitGroup
	var errs []error
	for i := range s.buf_size {
		if _, ok := s.cache_buf[s.sentenceNum+i]; !ok {
			wg.Go(func() {
				_, err := s.getWaveformData(i)
				errs = append(errs, err)
			})
		}
	}
	wg.Wait()
	for _, e := range errs {
		if e != nil {
			return e
		}
	}
	return nil
}

// Clean old entries from buffer cache.
func (s *Source) cleanBufferCache() {
	s.mut.Lock()
	defer s.mut.Unlock()
	for i := range s.sentenceNum {
		delete(s.cache_buf, i)
	}
	// TODO clean records ahead as well.
}

// Increment current sentence number returning updated
// value, returns -1 if number cannot be incremented.
func (s *Source) incrementSentenceNum() int {
	if s.sentenceNum > len(s.data)-1 {
		return -1
	}
	s.sentenceNum += 1
	return s.sentenceNum
}

// Decrement sentence num returning updated value,
// returns -1 if value cannot be decremented.
func (s *Source) decrementSentenceNum() int {
	if s.sentenceNum == 0 {
		return -1
	}
	s.sentenceNum -= 1
	return s.sentenceNum
}

// Representation of source as saved on disk.
type SourceData struct {
	Id   string
	Data []string
}

// Save text source as gob file.
func SaveTextSource(path, id string, data []byte) (string, error) {
	var buf bytes.Buffer
	err := gob.NewEncoder(&buf).Encode(SourceData{
		Data: sentencizer.Sentencize(data),
		Id:   id,
	})
	if err != nil {
		return "", err
	}
	p := filepath.Join(path, fmt.Sprintf("%s.gob", id))
	return p, os.WriteFile(p, buf.Bytes(), 0644)
}

// Load raw source from file.
func LoadTextSource(path string) (*SourceData, error) {
	f, err := os.OpenFile(path, os.O_RDONLY, 0644)
	defer f.Close()
	if err != nil {
		return nil, err
	}
	var result SourceData
	err = gob.NewDecoder(f).Decode(&result)
	return &result, err
}
